### ISSUE TITLE
util/atomic.h library not available

### ISSUE THREAD

**Issue by shivanksharma91** [jpiat/arduino#18]
hello

I was trying to go through this code, then i realized that this "util/atomic.h library is not available in arduino.
Can anyone help me in this? Where to find i and what does this library do?

**Comment by jpiat** [comment]
What version of Arduino IDE are you using ? What Arduino board are you
targeting ?

2016-11-14 15:08 GMT+01:00 shivanksharma91 notifications@github.com:

**Comment by shivanksharma91** [comment]
I am using arduino uno and Arduino IDE ver 1.6.13

**Comment by jpiat** [comment]
I just tried and it worked with arduino 1.6.12 which is the latest stable
version. Can you make sure that you have configured the IDE for arduino UNO
(Arduino/Genuino Uno should appear at the bottom left of the IDE window).

Regards,

Jonathan Piat

2016-11-15 11:44 GMT+01:00 shivanksharma91 notifications@github.com:

**Comment by shivanksharma91** [comment]
I don know, i followed each instruction correctly,but when i start the serial plotter i just see the "Start of receiver program" message and nothing else happens.
If possible can you please explain me how the Manchester encoding & decoding is being implemented in the provided code?

Regards

Shivank Sharma
